### ISSUE TITLE
Support #db/fn tagged

### ISSUE THREAD

**Issue by souenzzo** [JarrodCTaylor/schema-cartographer#22]
I tryied to upload my schema and this popup in my console:
Error: No reader function for tag db/fn.

https://github.com/JarrodCTaylor/schema-cartographer/blob/master/src/client/routes/index/view.cljs#L810

We can use `{:default tagged-literal}` ;)

**Comment by JarrodCTaylor** [comment]
Can you provide a minimal edn file that reproduces the error?

**Comment by souenzzo** [comment]
Can I refer this file?
https://docs.datomic.com/on-prem/database-functions.html#using-transaction-functions
`schema.edn`
```clojure
[{:db/ident :add-doc
  :db/fn #db/fn {:lang "clojure"
                 :params [db e doc]
                 :code [[:db/add e :db/doc doc]]}}]
```

**Comment by JarrodCTaylor** [comment]
I'd like for issues of this type to include a minimal Datomic schema used to create an example db and a minimal export file to be loaded into the ui. That will allow full understanding of the situation and facilitate the creation of proper tests.

**Comment by JarrodCTaylor** [comment]
This can be reopened if a reproducible example is provided.
