### ISSUE TITLE
Feature requests: visualization from raw schema files.

### ISSUE THREAD

**Issue by davidpham87** [JarrodCTaylor/schema-cartographer#27]
Hello,

Thanks a lot for the application and the library. I think the library is really useful. I wondered if it was possible to provide a raw schema file such as https://github.com/Datomic/mbrainz-sample/blob/master/schema.edn and get a simple visualization out of it? 

This feature would be useful for users who uses alternative to datomic (such as datahike and datascript).

Again, thanks a lot for your help!

Best regards,
David

**Comment by JarrodCTaylor** [comment]
The schema elements must be [annotated](https://github.com/JarrodCTaylor/schema-cartographer/pull/29) as described in the README in order to produce the visualization. It would not be possible to produce the same output given the file linked above.
