### ISSUE TITLE
shadow-cljs inspect namespaces have been migrated

### ISSUE THREAD

**Issue by daemianmack** [JarrodCTaylor/schema-cartographer#28]
When I clone SHA 8b59d16 and run the app with `clojure -A:cljs-dev`, I see the following...

```
[:app] Configuring build.
[:app] Compiling ...
[:app] Build failure:
The required namespace "shadow.remote.runtime.browser" is not available.
```

Updating the preload entry in shadow.cljs.edn's `[:builds :app :devtools :preloads]` value to reference "shadow.cljs.devtools.client.browser" instead seems like the thing to do. I'd submit a PR doing that, but I'm unable to test that it's correct because I get further compilation errors concerning reagent and re-frame-10x.

**Comment by JarrodCTaylor** [comment]
Sure enough, I was able to reproduce as well. Should be good to go now.
