### ISSUE TITLE
On-prem support?

### ISSUE THREAD

**Issue by conan** [JarrodCTaylor/schema-cartographer#31]
Hi, I can't seem to connect to an on-prem instance of Datomic.  Is there a way to do this, or does this tool only work with Datomic Cloud?  It looks like just what we need

**Comment by JarrodCTaylor** [comment]
The repository has been recently updated and now include support for on-prem

https://github.com/JarrodCTaylor/schema-cartographer/wiki/Create-a-schema-file-for-an-existing-unannotated-ON-PREM-database-from-a-REPL

**Comment by mprokopov** [comment]
Odd enough, but datomic-pro uses different client library. I managed to connect only by using exlcustions of references to client-cloud.
```clojure
{:deps
 {com.datomic/client-pro {:mvn/version "0.9.63"} ;; 0.9.57
  schema-cartographer/schema-cartographer {:mvn/version "1.0.0"
                                           :exclusions [com.datomic/client-cloud]
                                           }}}
```

But that threw me a new issue
```
Execution error (NullPointerException) at schema-cartographer.explorer/reduce-enumeration-references-namespaces$fn (explorer.clj:37).
Cannot invoke "clojure.lang.Named.getNamespace()" because "x" is null
Cannot invoke "clojure.lang.Named.getNamespace()" because "x" is n
```

**Comment by mprokopov** [comment]
I've prepared a small example for datomic on-prem, see https://github.com/mprokopov/cartographer-datomic-on-prem-example for details.

Key points to consider - run peer server, use different client library, and a small fix for namespace fn called with nil argument.
