### ISSUE TITLE
Website has invalid SSL cert

### ISSUE THREAD

**Issue by atroche** [JarrodCTaylor/schema-cartographer#34]
Hey, you probably already know, but just in case you don't:

```
❯ curl https://schema-cartographer.com/
curl: (60) SSL: no alternative certificate subject name matches target host name 'schema-cartographer.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. 
```

**Comment by JarrodCTaylor** [comment]
That is odd. The site has a valid certificate, and I do not have any issues accessing it through a browser or via curl. 

<img width="1119" alt="image" src="https://github.com/JarrodCTaylor/schema-cartographer/assets/4416952/f70b8844-2427-4972-a550-247280cc3eab">
